// Generated by scripts/sync_challenge_species_images.py.
// Do not edit by hand.
part of 'species_media.dart';

const Map<String, SpeciesMedia> generatedSpeciesMedia = {
  'pycnonotus sinensis': SpeciesMedia(
    assetPath: 'assets/species/pycnonotus_sinensis.webp',
    author: 'CharlesLam',
    license: 'CC BY-SA 2.0',
    sourceName: 'Wikimedia Commons',
    sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Light-vented_Bulbul2.jpg',
    referenceUrl:
        'https://ai.open.hhodata.com/species/bird/pycnonotus-sinensis/',
  ),
  'cuculus canorus': SpeciesMedia(
    assetPath: 'assets/species/cuculus_canorus.webp',
    author: 'GabrielBuissart',
    license: 'CC BY-SA 3.0',
    sourceName: 'Wikimedia Commons',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cuculus_canorus2.jpg',
    referenceUrl: 'https://www.wikidata.org/wiki/Q18845',
  ),
  'urocissa erythroryncha': SpeciesMedia(
    assetPath: 'assets/species/urocissa_erythroryncha.webp',
    author: 'Charles Lam from Hong Kong, China',
    license: 'CC BY-SA 2.0',
    sourceName: 'Wikimedia Commons',
    sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Urocissa_erythrorhyncha.jpg',
    referenceUrl: 'https://www.wikidata.org/wiki/Q766306',
  ),
  'passer montanus': SpeciesMedia(
    assetPath: 'assets/species/passer_montanus.webp',
    author: 'Andreas Trepte',
    license: 'CC BY-SA 2.5',
    sourceName: 'Wikimedia Commons',
    sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Tree-Sparrow-2009-16-02.jpg',
    referenceUrl: 'https://www.wikidata.org/wiki/Q25968',
  ),
  'horornis fortipes': SpeciesMedia(
    assetPath: 'assets/species/horornis_fortipes.webp',
    author: 'J.M.Garg',
    license: 'CC BY-SA 3.0',
    sourceName: 'Wikimedia Commons',
    sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Brownish-flanked_Bush_Warbler_I_IMG_6777.jpg',
    referenceUrl: 'https://www.wikidata.org/wiki/Q27075466',
  ),
  'copsychus saularis': SpeciesMedia(
    assetPath: 'assets/species/copsychus_saularis.webp',
    author: 'J.M.Garg',
    license: 'CC BY-SA 3.0',
    sourceName: 'Wikimedia Commons',
    sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Oriental_Magpie_Robin_(Copsychus_saularis)-_Male_at_Kolkata_I_IMG_3003.jpg',
    referenceUrl: 'https://www.wikidata.org/wiki/Q266761',
  ),
  'turdus mandarinus': SpeciesMedia(
    assetPath: 'assets/species/turdus_mandarinus.webp',
    author: 'zinogre',
    license: 'CC BY-SA 4.0',
    sourceName: 'Wikimedia Commons',
    sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Chinese_Blackbird,_Zhengzhou,_Henan,_China_09.jpg',
    referenceUrl: 'https://www.wikidata.org/wiki/Q20949808',
  ),
  'pica serica': SpeciesMedia(
    assetPath: 'assets/species/pica_serica.webp',
    author: 'Daniel Case',
    license: 'CC BY-SA 3.0',
    sourceName: 'Wikimedia Commons',
    sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Oriental_Magpie_on_Longevity_Hill,_Beijing.jpg',
    referenceUrl: 'https://www.wikidata.org/wiki/Q1133750',
  ),
  'spilopelia chinensis': SpeciesMedia(
    assetPath: 'assets/species/spilopelia_chinensis.webp',
    author: 'iNaturalist/ zinogre',
    license: 'CC BY-SA 4.0',
    sourceName: 'Wikimedia Commons',
    sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Spilopelia_chinensis_Zhengzhou_20210607.jpg',
    referenceUrl: 'https://www.wikidata.org/wiki/Q116686',
  ),
  'streptopelia chinensis': SpeciesMedia(
    assetPath: 'assets/species/spilopelia_chinensis.webp',
    author: 'iNaturalist/ zinogre',
    license: 'CC BY-SA 4.0',
    sourceName: 'Wikimedia Commons',
    sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Spilopelia_chinensis_Zhengzhou_20210607.jpg',
    referenceUrl: 'https://www.wikidata.org/wiki/Q116686',
  ),
  'lanius schach': SpeciesMedia(
    assetPath: 'assets/species/lanius_schach.webp',
    author: 'LiCheng Shih',
    license: 'CC BY 2.0',
    sourceName: 'Wikimedia Commons',
    sourceUrl:
        'https://commons.wikimedia.org/wiki/File:%E6%A3%95%E8%83%8C%E4%BC%AF%E5%8B%9E_(25040252703)_crop.jpg',
    referenceUrl: 'https://www.wikidata.org/wiki/Q795567',
  ),
  'abroscopus albogularis': SpeciesMedia(
    assetPath: 'assets/species/abroscopus_albogularis.webp',
    author: 'Francesco Veronesi from Italy',
    license: 'CC BY-SA 2.0',
    sourceName: 'Wikimedia Commons',
    sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Rufous-faced_Warbler_-_Bhutan_S4E0984_(19261554082)_(2).jpg',
    referenceUrl: 'https://www.wikidata.org/wiki/Q1589754',
  ),
  'mecopoda elongata': SpeciesMedia(
    assetPath: 'assets/species/mecopoda_elongata.webp',
    author: 'Manoj Karingamadathil',
    license: 'CC BY-SA 4.0',
    sourceName: 'iNaturalist',
    sourceUrl: 'https://www.inaturalist.org/photos/86944651',
    referenceUrl: 'https://www.inaturalist.org/taxa/366231',
  ),
  'cryptotympana atrata': SpeciesMedia(
    assetPath: 'assets/species/cryptotympana_atrata.webp',
    author: 'chiuluan',
    license: 'CC BY 4.0',
    sourceName: 'iNaturalist',
    sourceUrl: 'https://www.inaturalist.org/photos/134585922',
    referenceUrl: 'https://www.inaturalist.org/taxa/319989',
  ),
  'teleogryllus emma': SpeciesMedia(
    assetPath: 'assets/species/teleogryllus_emma.webp',
    author: 'harum.koh',
    license: 'CC BY-SA 4.0',
    sourceName: 'iNaturalist',
    sourceUrl: 'https://www.inaturalist.org/photos/1285060',
    referenceUrl: 'https://www.inaturalist.org/taxa/415442',
  ),
  'streeyola mongolica': SpeciesMedia(
    assetPath: 'assets/species/streeyola_mongolica.webp',
    author: 'TonyT',
    license: 'CC BY 4.0',
    sourceName: 'iNaturalist',
    sourceUrl: 'https://www.inaturalist.org/photos/537576347',
    referenceUrl: 'https://www.inaturalist.org/taxa/1650287',
  ),
  'velarifictorus micado': SpeciesMedia(
    assetPath: 'assets/species/velarifictorus_micado.webp',
    author: 'Benny Albro',
    license: 'CC BY 4.0',
    sourceName: 'iNaturalist',
    sourceUrl: 'https://www.inaturalist.org/photos/421681220',
    referenceUrl: 'https://www.inaturalist.org/taxa/146737',
  ),
  'pelophylax nigromaculatus': SpeciesMedia(
    assetPath: 'assets/species/pelophylax_nigromaculatus.webp',
    author: 'Kim, Hyun-tae',
    license: 'CC BY 4.0',
    sourceName: 'iNaturalist',
    sourceUrl: 'https://www.inaturalist.org/photos/47127806',
    referenceUrl: 'https://www.inaturalist.org/taxa/66330',
  ),
  'nidirana mangveni': SpeciesMedia(
    assetPath: 'assets/species/nidirana_mangveni.webp',
    author: 'angryphyco',
    license: 'CC BY 4.0',
    sourceName: 'iNaturalist',
    sourceUrl: 'https://www.inaturalist.org/photos/576268760',
    referenceUrl: 'https://www.inaturalist.org/taxa/1176938',
  ),
  'microhyla fissipes': SpeciesMedia(
    assetPath: 'assets/species/microhyla_fissipes.webp',
    author: 'Jaw-Jian La',
    license: 'CC BY 4.0',
    sourceName: 'iNaturalist',
    sourceUrl: 'https://www.inaturalist.org/photos/386287751',
    referenceUrl: 'https://www.inaturalist.org/taxa/66131',
  ),
  'fejervarya multistriata': SpeciesMedia(
    assetPath: 'assets/species/fejervarya_multistriata.webp',
    author: 'Wang.QG',
    license: 'CC BY 4.0',
    sourceName: 'iNaturalist',
    sourceUrl: 'https://www.inaturalist.org/photos/154118078',
    referenceUrl: 'https://www.inaturalist.org/taxa/120791',
  ),
};
