# Generated by scripts/generate_prompt_catalog.py. Do not edit by hand.
from __future__ import annotations

import re
from typing import Any


PROMPT_CATALOG_DIGEST = 'c5345e4b5538205c'
PROMPT_VERSIONS = {'creation': 'creation-v2',
 'parent_guidance': 'parent-guidance-v4',
 'story': 'animal-story-v5',
 'wan3_experiments': 'wan3-experiments-v1'}
PROMPT_GENERATION = {'creation': {},
 'parent_guidance': {'enable_thinking': False,
                     'initial_temperature': 0.85,
                     'max_completion_tokens': 900,
                     'response_format': 'json_object',
                     'retry_temperature': 0.75},
 'story': {'enable_thinking': False,
           'max_completion_tokens': 500,
           'response_format': 'json_object',
           'temperature': 0.6},
 'wan3_experiments': {}}
_PROMPTS = {'creation.mobile_music': {'text': '为儿童自然观察创作一段温柔、清澈、富有呼吸感的纯音乐。地点是{{ location }}，声音主题是{{ subject '
                                   '}}。以木琴、轻柔弦乐、原声打击乐和空气感铺底，不要人声，不要歌词，不要戏剧化高潮，给自然原声留出空间。',
                           'variables': ('location', 'subject')},
 'creation.mobile_narration': {'text': '在{{ location }}，我们听见了{{ subject '
                                       '}}。每一种自然声音，都在告诉我们环境正在发生什么。再安静听一听，它的节奏有没有变化？',
                               'variables': ('location', 'subject')},
 'creation.mobile_video_bird': {'text': '生成单镜头。清晨的中国{{ location }}城市公园，一只{{ subject '
                                        '}}侧身站在横向树枝上，轻轻转头一次。固定机位，中长焦中景，浅景深，柔和自然光，真实野生动物纪录片，动作缓慢自然，身体和脚爪结构准确，画面稳定。',
                                'variables': ('location', 'subject')},
 'creation.mobile_video_environment': {'text': '生成单镜头。雨后清晨的中国{{ location '
                                               '}}城市公园自然环境，低机位看向安静的草地和浅水岸边。水面出现轻微涟漪，草叶和树叶随微风缓慢摆动，远处树影柔和虚化。固定机位，柔和自然光，真实自然纪录片，画面稳定，环境中没有可见动物。',
                                       'variables': ('location',)},
 'creation.mobile_video_frog': {'text': '生成单镜头。雨后的中国{{ location }}城市公园湿地，一只{{ subject '
                                        '}}安静伏在浅水边，缓慢眨眼一次，附近水面出现一圈轻微涟漪。固定机位，贴近水面的低机位中景，柔和阴天自然光，真实野生动物纪录片，四肢和身体结构准确，动作缓慢自然，画面稳定。',
                                'variables': ('location', 'subject')},
 'creation.mobile_video_negative': {'text': '字幕，水印以外的文字和标志，人物，儿童正脸，笼养，捕捉动物，触摸动物，多只重复动物，额外肢体，额外翅膀，肢体融合，畸形，身体闪烁，形态突变，低清晰度',
                                    'variables': ()},
 'creation.server_music': {'text': '纯音乐，无人声，以{{ primary '
                                   '}}为灵感，自然、轻盈、好奇的儿童探索氛围，柔和木琴、钢琴、轻打击乐，简单原创旋律，舒缓中速，适合作为亲子自然观察短片背景音乐，避免宏大、紧张、悲伤和密集鼓点。',
                           'variables': ('primary',)},
 'creation.server_narration': {'text': '在{{ location }}，我们听见了{{ primary }}。{{ short_fact }}。{{ '
                                       'observation_summary }}。这是一条调查线索，不是最终鉴定。',
                               'variables': ('location',
                                             'primary',
                                             'short_fact',
                                             'observation_summary')},
 'creation.server_video': {'text': '生成一支9:16竖屏、无字幕、无文字、无人物特写的儿童自然科普短片。地点氛围：中国杭州城市公园。主题：{{ title '
                                   '}}，主要声音线索：{{ primary }}。调查状态：{{ status }}；现场观察摘要：{{ '
                                   'observation_summary }}；不确定性：{{ uncertainty }}。画面表达：{{ '
                                   'explanation }} '
                                   '镜头缓慢、真实自然、柔和日光、纪录片质感，不捕捉、不触摸、不追逐动物；如无法确定具体物种，只表现环境线索，不出现具体动物近景。',
                           'variables': ('title',
                                         'primary',
                                         'status',
                                         'observation_summary',
                                         'uncertainty',
                                         'explanation')},
 'creation.server_video_negative': {'text': '字幕，文字，水印以外的标识，儿童正脸，捕捉动物，触摸动物，畸形，低清晰度',
                                    'variables': ()},
 'creation.server_video_timed': {'text': '生成一支{{ duration_seconds }}秒短片。{{ video_prompt }}',
                                 'variables': ('duration_seconds', 'video_prompt')},
 'parent_guidance.correction': {'text': '\n'
                                        '\n'
                                        '上一次输出已被拒绝，原因：{{ validation_error '
                                        '}}。请完全重写JSON，删除没有真实行为依据的内容。',
                                'variables': ('validation_error',)},
 'parent_guidance.system': {'text': '你是亲子自然教育陪伴编辑。真实行为证据、安全和儿童自主性高于文采。', 'variables': ()},
 'parent_guidance.user': {'text': '请直接为一位正在陪孩子进行自然声音调查的家长生成现场引导和过程性夸奖。\n'
                                  '\n'
                                  '候选：{{ candidate_name }}\n'
                                  '声音类别：{{ category }}\n'
                                  '模型分数：{{ confidence }}，这不是准确率\n'
                                  '录音是否为弱动态信号：{{ weak_signal }}\n'
                                  '孩子/家庭实际填写的观察：{{ observations }}\n'
                                  '本次真实发生的行为：\n'
                                  '{{ behavior_lines }}\n'
                                  '\n'
                                  '你必须直接创作自然、具体、不重复的中文表达。每句夸奖必须严格依据上面的真实行为，并在evidence_behavior中逐字返回对应ID。不得虚构孩子看见动物、留在步道、认真比较、重新录音等没有列出的行为。不得把候选写成确定答案。引导只能鼓励远距离倾听和观看，不得鼓励追逐、捕捉、触摸、投喂、拨开灌木、爬树、下水或靠近巢穴。安全提醒应写在avoid字段；如果say或action必须提及危险动作，必须使用“不要、避免、无需、不能”等明确否定表达。避免“你真棒、太聪明、小天才”等空泛评价。\n'
                                  '\n'
                                  '如果真实行为中没有observedSafely，夸奖文本和能力标签不得提及安全、步道、追逐、捕捉、触摸、投喂或“没有靠近”等安全表现；这些词只允许出现在guide的avoid字段中。只有evidence_behavior为capturedSound时才能说孩子按下录音键、现场录下声音；importedSound只能表述为选择或导入了已有声音；旧版recordedSound不得自行判断是哪一种。\n'
                                  '\n'
                                  '返回JSON，不要Markdown：\n'
                                  '{"guides":[{"goal":"目标","say":"家长可以直接说的话","action":"一起做的动作","avoid":"需要避免的做法"}],"praises":[{"evidence_behavior":"真实行为ID","ability":"能力标签","text":"家长可以直接说的具体夸奖"}]}\n'
                                  'guides必须2至3条，praises必须3至5条。',
                          'variables': ('candidate_name',
                                        'category',
                                        'confidence',
                                        'weak_signal',
                                        'observations',
                                        'behavior_lines')},
 'story.system': {'text': '你是儿童自然教育故事编辑。事实边界、安全和候选状态高于故事性。', 'variables': ()},
 'story.user': {'text': '请为6至12岁儿童创作一则关于候选动物的中文科普故事。\n'
                        '候选动物：{{ candidate_name }}\n'
                        '学名：{{ scientific_name }}\n'
                        '候选层级：{{ candidate_status }}\n'
                        '声音大类：{{ category }}\n'
                        '区域背景：{{ location }}，仅表示项目服务区域，不得虚构西湖、植物园、公园、池塘、芦苇荡等具体采集地点\n'
                        '故事主题：{{ angle }}\n'
                        '用户本次实际选择的现场观察：{{ observation_text }}\n'
                        '\n'
                        '当前没有外部物种知识库。请严格遵守下列规则：\n'
                        '1. 标题和正文第一句都必须出现“{{ candidate_name }}”。\n'
                        '2. 正文必须逐字出现全部现场观察标签：{{ observation_text }}。只能把它们写成这次相遇当时留下的线索。\n'
                        '3. 故事只发生在用户选中的时段，不得换成或延伸到其他时段。\n'
                        '4. '
                        '除现场标签外，不得补写外形、颜色、食物、捕食、休息、求偶、同伴交流、领地、繁殖、具体动作、拟声词或标志性特征。不得写精确数字、保护等级、生态指标、绝对习性或未核验结论。\n'
                        '5. 候选层级为category_only时，主角只能称为“{{ candidate_name '
                        '}}候选者”，不得补成具体物种。所有故事都不得声称已确认物种。\n'
                        '6. 不得鼓励追逐、捕捉、触摸、投喂、爬树、下水或靠近巢穴，观察建议只能是远距离倾听和观看。\n'
                        '7. '
                        '在“跟随一次声音的出现与消失”“从一个自然问题展开”“描写一段短暂相遇”中选一种叙事。避免“歌唱家”“音符”“音乐会”“自然舞台”“生命力”等套话。\n'
                        '8. 任何字段都不得使用Markdown符号。\n'
                        '\n'
                        '返回JSON，不要Markdown：\n'
                        '{"title":"4至28字","story":"120至260字，只根据现场线索讲一段有画面感的动物故事","observations_used":["逐字复制全部用户现场观察标签"],"observation_prompt":"一句安全、远距离、可执行的下次观察任务"}',
                'variables': ('candidate_name',
                              'scientific_name',
                              'candidate_status',
                              'category',
                              'location',
                              'angle',
                              'observation_text')},
 'wan3_experiments.concise_sparrow': {'text': '生成单镜头。清晨杭州公园，一只树麻雀侧身站在横向树枝上，轻轻转头一次。固定机位，中长焦中景，浅景深，柔和自然光，真实野生动物纪录片，动作缓慢自然，身体和脚爪结构准确，画面稳定。',
                                      'variables': ()},
 'wan3_experiments.current_mobile_baseline': {'text': '生成一支5秒的竖屏儿童自然科普短片。地点氛围：中国杭州的城市公园，主题声音：树麻雀。清晨薄雾、柔和自然光、真实纪录片质感、缓慢稳定镜头。只展示环境和声音线索，不出现文字、字幕、儿童正脸，不表现捕捉或触摸野生动物。不确定具体物种时不要生成动物近景。',
                                              'variables': ()},
 'wan3_experiments.negative': {'text': '字幕，文字，标志，儿童正脸，人物，笼养，捕捉动物，触摸动物，多只重复动物，额外肢体，额外翅膀，肢体融合，畸形，身体闪烁，形态突变，低清晰度',
                               'variables': ()},
 'wan3_experiments.structured_frog': {'text': '生成单镜头。雨后的杭州城市公园湿地，贴近水面的低机位中景，一只黑斑侧褶蛙安静伏在浅水边，身体侧向镜头，四肢轮廓自然完整。青蛙保持静止，缓慢眨眼一次，一滴水落在附近形成一圈轻微涟漪，岸边湿润草叶小幅摆动。固定机位，柔和阴天自然光，浅景深，真实野生动物纪录片风格，物种外形准确，皮肤纹理自然，动作缓慢稳定。',
                                      'variables': ()},
 'wan3_experiments.structured_sparrow': {'text': '生成单镜头。清晨的杭州城市公园，中长焦中景，一只树麻雀侧身停在一根横向树枝上，位于画面中部，身体、双脚和尾羽完整可见。树麻雀保持站立，轻轻转头一次，胸羽随呼吸小幅起伏，附近几片树叶被微风轻轻吹动。固定机位，浅景深，柔和自然光，背景安静虚化。真实野生动物纪录片质感，物种外形准确，身体比例自然，动作缓慢克制，画面连续稳定。',
                                         'variables': ()},
 'wan3_experiments.uncertain_environment': {'text': '生成单镜头。雨后清晨的杭州城市公园湿地，低机位看向安静的浅水岸边。水面出现两圈轻微涟漪，芦苇和湿润草叶随微风缓慢摆动，远处树影柔和虚化。固定机位，柔和阴天自然光，真实自然纪录片质感，画面连续稳定，环境中没有可见动物。',
                                            'variables': ()}}
_UNRESOLVED_VARIABLE = re.compile(r"\{\{\s*[a-zA-Z_][a-zA-Z0-9_]*\s*\}\}")


def prompt_version(namespace: str) -> str:
    try:
        return PROMPT_VERSIONS[namespace]
    except KeyError as exc:
        raise KeyError(f"Unknown prompt namespace: {namespace}") from exc


def prompt_generation(namespace: str) -> dict[str, Any]:
    try:
        return dict(PROMPT_GENERATION[namespace])
    except KeyError as exc:
        raise KeyError(f"Unknown prompt generation profile: {namespace}") from exc


def render_prompt(key: str, **variables: object) -> str:
    try:
        entry = _PROMPTS[key]
    except KeyError as exc:
        raise KeyError(f"Unknown prompt key: {key}") from exc
    required = set(entry["variables"])
    supplied = set(variables)
    if required != supplied:
        missing = sorted(required - supplied)
        extra = sorted(supplied - required)
        raise ValueError(f"Prompt {key} variables mismatch: missing={missing}, extra={extra}")
    rendered = entry["text"]
    for name in entry["variables"]:
        rendered = re.sub(
            r"\{\{\s*" + re.escape(name) + r"\s*\}\}",
            lambda _match, value=str(variables[name]): value,
            rendered,
        )
    if _UNRESOLVED_VARIABLE.search(rendered):
        raise ValueError(f"Prompt {key} contains unresolved variables")
    return rendered
