from __future__ import annotations

import argparse
import hashlib
import json
import os
import pprint
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
PROMPT_DIR = ROOT / "config" / "prompts"
PYTHON_OUTPUT = ROOT / "app" / "generated_prompts.py"
DART_OUTPUT = ROOT / "mobile" / "lib" / "core" / "ai" / "generated_prompts.dart"
VARIABLE_PATTERN = re.compile(r"\{\{\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\}\}")


@dataclass(frozen=True)
class PromptEntry:
    key: str
    text: str
    variables: tuple[str, ...]
    targets: tuple[str, ...]


@dataclass(frozen=True)
class PromptCatalog:
    digest: str
    versions: dict[str, str]
    entries: dict[str, PromptEntry]
    generation: dict[str, dict[str, Any]]


def load_catalog() -> PromptCatalog:
    paths = sorted(PROMPT_DIR.glob("*.yaml"))
    if not paths:
        raise ValueError(f"Prompt directory is empty: {PROMPT_DIR}")
    versions: dict[str, str] = {}
    entries: dict[str, PromptEntry] = {}
    generation: dict[str, dict[str, Any]] = {}
    digest = hashlib.sha256()
    for path in paths:
        source = path.read_bytes()
        digest.update(path.name.encode("utf-8"))
        digest.update(b"\0")
        digest.update(source)
        document = yaml.safe_load(source)
        if not isinstance(document, dict):
            raise ValueError(f"{path} must contain one YAML object")
        namespace = _required_string(document, "namespace", path)
        version = _required_string(document, "version", path)
        if namespace in versions:
            raise ValueError(f"Duplicate prompt namespace: {namespace}")
        versions[namespace] = version
        raw_targets = document.get("targets", ["python", "dart"])
        if not isinstance(raw_targets, list) or not raw_targets:
            raise ValueError(f"{path} targets must be a non-empty list")
        targets = tuple(str(item) for item in raw_targets)
        if not set(targets).issubset({"python", "dart"}):
            raise ValueError(f"{path} has unsupported targets: {targets}")
        raw_prompts = document.get("prompts")
        if not isinstance(raw_prompts, dict) or not raw_prompts:
            raise ValueError(f"{path} must define prompts")
        for name, raw_entry in raw_prompts.items():
            if not isinstance(name, str) or not isinstance(raw_entry, dict):
                raise ValueError(f"Invalid prompt entry in {path}: {name!r}")
            key = f"{namespace}.{name}"
            if key in entries:
                raise ValueError(f"Duplicate prompt key: {key}")
            text = _required_string(raw_entry, "text", path)
            raw_variables = raw_entry.get("variables", [])
            if not isinstance(raw_variables, list) or not all(
                isinstance(item, str) and item for item in raw_variables
            ):
                raise ValueError(f"{key} variables must be a string list")
            variables = tuple(raw_variables)
            if len(set(variables)) != len(variables):
                raise ValueError(f"{key} declares duplicate variables")
            referenced = set(VARIABLE_PATTERN.findall(text))
            declared = set(variables)
            if referenced != declared:
                raise ValueError(
                    f"{key} variable mismatch: declared={sorted(declared)}, "
                    f"referenced={sorted(referenced)}"
                )
            entries[key] = PromptEntry(
                key=key,
                text=text,
                variables=variables,
                targets=targets,
            )
        raw_generation = document.get("generation", {})
        if not isinstance(raw_generation, dict):
            raise ValueError(f"{path} generation must be an object")
        generation[namespace] = raw_generation
    return PromptCatalog(
        digest=digest.hexdigest()[:16],
        versions=versions,
        entries=entries,
        generation=generation,
    )


def _required_string(value: dict[str, Any], key: str, path: Path) -> str:
    result = value.get(key)
    if not isinstance(result, str) or not result:
        raise ValueError(f"{path} field {key!r} must be a non-empty string")
    return result


def render_python(catalog: PromptCatalog) -> str:
    prompts = {
        key: {"text": entry.text, "variables": entry.variables}
        for key, entry in catalog.entries.items()
        if "python" in entry.targets
    }
    return f'''# Generated by scripts/generate_prompt_catalog.py. Do not edit by hand.
from __future__ import annotations

import re
from typing import Any


PROMPT_CATALOG_DIGEST = {catalog.digest!r}
PROMPT_VERSIONS = {pprint.pformat(catalog.versions, sort_dicts=True, width=100)}
PROMPT_GENERATION = {pprint.pformat(catalog.generation, sort_dicts=True, width=100)}
_PROMPTS = {pprint.pformat(prompts, sort_dicts=True, width=100)}
_UNRESOLVED_VARIABLE = re.compile(r"\\{{\\{{\\s*[a-zA-Z_][a-zA-Z0-9_]*\\s*\\}}\\}}")


def prompt_version(namespace: str) -> str:
    try:
        return PROMPT_VERSIONS[namespace]
    except KeyError as exc:
        raise KeyError(f"Unknown prompt namespace: {{namespace}}") from exc


def prompt_generation(namespace: str) -> dict[str, Any]:
    try:
        return dict(PROMPT_GENERATION[namespace])
    except KeyError as exc:
        raise KeyError(f"Unknown prompt generation profile: {{namespace}}") from exc


def render_prompt(key: str, **variables: object) -> str:
    try:
        entry = _PROMPTS[key]
    except KeyError as exc:
        raise KeyError(f"Unknown prompt key: {{key}}") from exc
    required = set(entry["variables"])
    supplied = set(variables)
    if required != supplied:
        missing = sorted(required - supplied)
        extra = sorted(supplied - required)
        raise ValueError(f"Prompt {{key}} variables mismatch: missing={{missing}}, extra={{extra}}")
    rendered = entry["text"]
    for name in entry["variables"]:
        rendered = re.sub(
            r"\\{{\\{{\\s*" + re.escape(name) + r"\\s*\\}}\\}}",
            lambda _match, value=str(variables[name]): value,
            rendered,
        )
    if _UNRESOLVED_VARIABLE.search(rendered):
        raise ValueError(f"Prompt {{key}} contains unresolved variables")
    return rendered
'''


def _dart_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False).replace("$", r"\$")


def _dart_value(value: Any, indent: int = 0) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return _dart_string(value)
    if isinstance(value, list):
        return "<Object?>[" + ", ".join(_dart_value(item, indent) for item in value) + "]"
    if isinstance(value, dict):
        padding = " " * indent
        inner = " " * (indent + 2)
        rows = [
            f"{inner}{_dart_string(str(key))}: {_dart_value(item, indent + 2)},"
            for key, item in sorted(value.items())
        ]
        return "<String, Object?>{\n" + "\n".join(rows) + f"\n{padding}}}"
    raise TypeError(f"Unsupported Dart value: {value!r}")


def render_dart(catalog: PromptCatalog) -> str:
    dart_namespaces = {
        entry.key.split(".", 1)[0]
        for entry in catalog.entries.values()
        if "dart" in entry.targets
    }
    version_rows = "\n".join(
        f"    {_dart_string(key)}: {_dart_string(value)},"
        for key, value in sorted(catalog.versions.items())
        if key in dart_namespaces
    )
    prompt_rows = []
    for key, entry in sorted(catalog.entries.items()):
        if "dart" not in entry.targets:
            continue
        variables = ", ".join(_dart_string(item) for item in entry.variables)
        prompt_rows.append(
            f"    {_dart_string(key)}: _PromptTemplate(\n"
            f"      text: {_dart_string(entry.text)},\n"
            f"      variables: <String>[{variables}],\n"
            "    ),"
        )
    generation_rows = "\n".join(
        f"    {_dart_string(key)}: {_dart_value(value, 4)},"
        for key, value in sorted(catalog.generation.items())
        if key in dart_namespaces
    )
    return f'''// Generated by scripts/generate_prompt_catalog.py. Do not edit by hand.

final class AiPromptCatalog {{
  AiPromptCatalog._();

  static const digest = {_dart_string(catalog.digest)};

  static const versions = <String, String>{{
{version_rows}
  }};

  static const generation = <String, Map<String, Object?>>{{
{generation_rows}
  }};

  static const _prompts = <String, _PromptTemplate>{{
{chr(10).join(prompt_rows)}
  }};

  static String version(String namespace) {{
    final value = versions[namespace];
    if (value == null) {{
      throw ArgumentError.value(namespace, 'namespace', 'Unknown prompt namespace');
    }}
    return value;
  }}

  static String render(String key, Map<String, Object?> variables) {{
    final template = _prompts[key];
    if (template == null) {{
      throw ArgumentError.value(key, 'key', 'Unknown prompt key');
    }}
    final required = template.variables.toSet();
    final supplied = variables.keys.toSet();
    if (required.length != supplied.length || !required.containsAll(supplied)) {{
      final missing = required.difference(supplied).toList()..sort();
      final extra = supplied.difference(required).toList()..sort();
      throw ArgumentError('Prompt $key variables mismatch: missing=$missing, extra=$extra');
    }}
    var result = template.text;
    for (final name in template.variables) {{
      result = result.replaceAll(RegExp(r'\\{{\\{{\\s*' + RegExp.escape(name) + r'\\s*\\}}\\}}'), variables[name].toString());
    }}
    if (RegExp(r'\\{{\\{{\\s*[a-zA-Z_][a-zA-Z0-9_]*\\s*\\}}\\}}').hasMatch(result)) {{
      throw ArgumentError('Prompt $key contains unresolved variables');
    }}
    return result;
  }}
}}

final class _PromptTemplate {{
  const _PromptTemplate({{required this.text, required this.variables}});

  final String text;
  final List<String> variables;
}}
'''


def write_or_check(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return True
    if check:
        print(f"Prompt catalog output is stale: {path.relative_to(ROOT)}")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"Generated {path.relative_to(ROOT)}")
    return True


def write_or_check_dart(catalog: PromptCatalog, content: str, check: bool) -> bool:
    dart = _find_dart()
    if dart:
        formatted = _format_dart_content(content, dart)
        return write_or_check(DART_OUTPUT, formatted, check)
    if check:
        if not DART_OUTPUT.exists():
            print(f"Prompt catalog output is missing: {DART_OUTPUT.relative_to(ROOT)}")
            return False
        marker = f'static const digest = "{catalog.digest}";'
        if marker not in DART_OUTPUT.read_text(encoding="utf-8"):
            print(f"Prompt catalog output is stale: {DART_OUTPUT.relative_to(ROOT)}")
            return False
        return True
    write_or_check(DART_OUTPUT, content, check=False)
    return True


def _format_dart_content(content: str, dart: str) -> str:
    with tempfile.TemporaryDirectory(prefix="prompt-catalog-") as raw_directory:
        path = Path(raw_directory) / "generated_prompts.dart"
        path.write_text(content, encoding="utf-8", newline="\n")
        subprocess.run(
            [dart, "format", str(path)],
            cwd=ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
        return path.read_text(encoding="utf-8")


def _find_dart() -> str | None:
    configured = os.getenv("DART", "").strip()
    if configured:
        return configured
    discovered = shutil.which("dart")
    if discovered:
        return discovered
    user_profile = os.getenv("USERPROFILE", "")
    if user_profile:
        candidate = Path(user_profile) / "development" / "flutter" / "bin" / "dart.bat"
        if candidate.is_file():
            return str(candidate)
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Python and Dart prompt catalogs from YAML.")
    parser.add_argument("--check", action="store_true", help="Fail when generated outputs are stale.")
    args = parser.parse_args()
    catalog = load_catalog()
    valid = all(
        [
            write_or_check(PYTHON_OUTPUT, render_python(catalog), args.check),
            write_or_check_dart(catalog, render_dart(catalog), args.check),
        ]
    )
    return 0 if valid else 1


if __name__ == "__main__":
    raise SystemExit(main())
